#!/bin/bash

emerge --sync
cp /root/lo-bin-build/config/world /var/lib/portage/world
emerge -uDNv --with-bdeps=y world
emerge --depclean
emerge @preserved-rebuild
revdep-rebuild
emerge -uDNv --with-bdeps=y world
