#!/bin/bash

# important: you need to use the most general CFLAGS to build the packages:
#  * for x86  : CFLAGS="-march=i586 -mtune=generic -O2 -pipe -g"
#  * for amd64: CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -g"

# What you can set:
VERSION="7.4.6.2"
BINVERSION="7.4.6.2"

################################################

BASEDIR=/root/lo-bin-build

USEFILE="/etc/portage/package.use/libreo"
MYPKGDIR="$( portageq pkgdir )"
MYTMPDIR=$BASEDIR/tmp
MYDISTDIR=$BASEDIR/distfiles

################################################


OPTS="-v"

# bug 473974
export LC_MESSAGES=C

# make sure we're updated
/root/lo-bin-build/cleanup

die() {
        echo "${1}"
        exit 1
}

if [ "$( uname -m )" = "x86_64" ] ; then
	ARCH="amd64"
elif [ "$( uname -m )" = "i686" ] ; then
	ARCH="x86"
else
	die "Arch $( uname -m ) not supported"
fi

# first the default subset of useflags
IUSES_BASE="branding cups dbus googledrive gstreamer mariadb odk -accessibility -base -bluetooth -coinmp -debug -firebird -gltf -gtk2 -jemalloc -ldap -pdfimport -postgres"

ENABLE_EXTENSIONS="presenter-console"
DISABLE_EXTENSIONS="nlpsolver scripting-beanshell scripting-javascript wiki-publisher"

for lo_xt in ${ENABLE_EXTENSIONS}; do
        IUSES_BASE+=" libreoffice_extensions_${lo_xt}"
done
for lo_xt in ${DISABLE_EXTENSIONS}; do
        IUSES_BASE+=" -libreoffice_extensions_${lo_xt}"
done
unset lo_xt

# now for the options
IUSES_J="-base java libreoffice_extensions_nlpsolver"
IUSES_NJ="-java -base"
IUSES_G="eds"
IUSES_NG="-eds"
IUSES_K="kde -gtk"
IUSES_NK="-kde gtk"

if [ -f /etc/portage/package.use ] ; then
	die "Please save your package.use and re-create it as a directory"
fi

mkdir -p /etc/portage/package.use/ || die

mkdir -p "${MYPKGDIR}"
if [ -z "${MYPKGDIR}" -o ! -d "${MYPKGDIR}" ] ; then
	die "Anything goes wrong"
fi

echo "Base"
echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_NJ} ${IUSES_NG} ${IUSES_NK}" > ${USEFILE}
emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
quickpkg libreoffice --include-config=y
mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-${BINVERSION}.tbz2  || die "Moving package failed"

if [ ${ARCH} = "amd64" ]; then
	echo "Base - java"
	echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_J} ${IUSES_NG} ${IUSES_NK}" > ${USEFILE}
	emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
	quickpkg libreoffice --include-config=y
	mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-java-${BINVERSION}.tbz2  || die "Moving package failed"
fi

echo "KDE"
echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_NJ} ${IUSES_NG} ${IUSES_K}" > ${USEFILE}
emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
quickpkg libreoffice --include-config=y
mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-kde-${BINVERSION}.tbz2  || die "Moving package failed"

if [ ${ARCH} = "amd64" ]; then
	echo "KDE - java"
	echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_J} ${IUSES_NG} ${IUSES_K}" > ${USEFILE}
	emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
	quickpkg libreoffice --include-config=y
	mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-kde-java-${BINVERSION}.tbz2  || die "Moving package failed"
fi

echo "Gnome"
echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_NJ} ${IUSES_G} ${IUSES_NK}" > ${USEFILE}
emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
quickpkg libreoffice --include-config=y
mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-gnome-${BINVERSION}.tbz2  || die "Moving package failed"

if [ ${ARCH} = "amd64" ]; then
	echo "Gnome -java"
	echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_J} ${IUSES_G} ${IUSES_NK}" > ${USEFILE}
	emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
	quickpkg libreoffice --include-config=y
	mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-gnome-java-${BINVERSION}.tbz2  || die "Moving package failed"
fi

cd ${MYTMPDIR}

for name in ./libreoffice*-${BINVERSION}.tbz2 ; do

  BN=`basename $name .tbz2`

  rm -rf tmp.lo
  mkdir -vp tmp.lo/p1 tmp.lo/p2
  cd tmp.lo/p1

  echo "Unpacking complete archive $BN.tbz2"
  tar xfvjp ../../$BN.tbz2

  echo "Moving debug info"
  mkdir -vp ../p2/usr/lib
  mv -v usr/lib/debug ../p2/usr/lib/

  echo "Re-packing program"
  tar cfv ../../$ARCH-bin-$BN.tar --owner root --group root ./*

  echo "Re-packing debug info"
  cd ../p2
  tar cfv ../../$ARCH-debug-$BN.tar --owner root --group root ./*

  echo "Removing unpacked files"
  cd ../..
  rm -rf tmp.lo

  echo "Removing original package file"
  rm -f $BN.tbz2

  echo "Done with $BN.tbz2"

done

cd ${MYTMPDIR}

for package in bin debug ; do

 for suffix in java kde kde-java gnome gnome-java ; do

  if [ ${ARCH} = "amd64" ] || [ ! ${suffix} = *java ] ; then

    echo "Generating binary diffs"
    xdelta3 -9 -s ${ARCH}-${package}-libreoffice-${BINVERSION}.tar ${ARCH}-${package}-libreoffice-${suffix}-${BINVERSION}.tar $ARCH-${package}-libreoffice-${suffix}-${BINVERSION}.xd3
    rm ${ARCH}-${package}-libreoffice-${suffix}-${BINVERSION}.tar
    mv -v $ARCH-${package}-libreoffice-${suffix}-${BINVERSION}.xd3 $MYDISTDIR

 fi

 done

 echo "Compressing base package"
 xz -9 ${ARCH}-${package}-libreoffice-${BINVERSION}.tar
 mv -v ${ARCH}-${package}-libreoffice-${BINVERSION}.tar.xz $MYDISTDIR

done

rm -f ${USEFILE} || die "Removing ${USEFILE} failed"

cd ${MYDISTDIR}
${BASEDIR}/manifest ${ARCH}-* > Manifest-${ARCH}.txt

emerge --info > Info-${ARCH}.txt
equery list '*' >> Info-${ARCH}.txt
