#!/bin/bash

# important: you need to use the most general CFLAGS to build the packages:
#  * for x86  : CFLAGS="-march=i586 -mtune=generic -O2 -pipe -g"
#  * for amd64: CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -g"

# What you can set:
VERSION="4.1.3.2"
BINVERSION="4.1.3.2"

################################################

BASEDIR=/root/lo-bin-build

USEFILE="/etc/portage/package.use/libreo"
MYPKGDIR="$( portageq pkgdir )"
MYTMPDIR=$BASEDIR/tmp
MYDISTDIR=$BASEDIR/distfiles

################################################


OPTS="-v"

# bug 473974
export LC_MESSAGES=C

die() {
        echo "${1}"
        exit 1
}

if [ "$( uname -m )" = "x86_64" ] ; then
	ARCH="amd64"
elif [ "$( uname -m )" = "i686" ] ; then
	ARCH="x86"
else
	die "Arch $( uname -m ) not supported"
fi

# first the default subset of useflags
IUSES_BASE="bash-completion branding cups dbus gstreamer gtk opengl vba webdav -aqua -binfilter -bluetooth -debug -gtk3 -jemalloc -mysql -odk -postgres -telepathy"

ENABLE_EXTENSIONS="presenter-console presenter-minimizer"
DISABLE_EXTENSIONS="nlpsolver pdfimport scripting-beanshell scripting-javascript wiki-publisher"

for lo_xt in ${ENABLE_EXTENSIONS}; do
        IUSES_BASE+=" libreoffice_extensions_${lo_xt}"
done
for lo_xt in ${DISABLE_EXTENSIONS}; do
        IUSES_BASE+=" -libreoffice_extensions_${lo_xt}"
done
unset lo_xt

# now for the options
IUSES_J="java libreoffice_extensions_nlpsolver"
IUSES_NJ="-java"
IUSES_G="gnome eds"
IUSES_NG="-gnome -eds"
IUSES_K="kde"
IUSES_NK="-kde"

if [ -f /etc/portage/package.use ] ; then
	die "Please save your package.use and re-create it as a directory"
fi

mkdir -p /etc/portage/package.use/ || die

mkdir -p "${MYPKGDIR}"
if [ -z "${MYPKGDIR}" -o ! -d "${MYPKGDIR}" ] ; then
	die "Anything goes wrong"
fi

# compile the flavor
echo "Base"
echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_NJ} ${IUSES_NG} ${IUSES_NK}" > ${USEFILE}
emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
quickpkg libreoffice --include-config=y
mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-${BINVERSION}.tbz2  || die "Moving package failed"

echo "Base - java"
echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_J} ${IUSES_NG} ${IUSES_NK}" > ${USEFILE}
emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
quickpkg libreoffice --include-config=y
mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-java-${BINVERSION}.tbz2  || die "Moving package failed"

# kde flavor
echo "KDE"
echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_NJ} ${IUSES_NG} ${IUSES_K}" > ${USEFILE}
emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
quickpkg libreoffice --include-config=y
mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-kde-${BINVERSION}.tbz2  || die "Moving package failed"

echo "KDE - java"
echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_J} ${IUSES_NG} ${IUSES_K}" > ${USEFILE}
emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
quickpkg libreoffice --include-config=y
mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-kde-java-${BINVERSION}.tbz2  || die "Moving package failed"

# gnome flavor
echo "Gnome"
echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_NJ} ${IUSES_G} ${IUSES_NK}" > ${USEFILE}
emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
quickpkg libreoffice --include-config=y
mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-gnome-${BINVERSION}.tbz2  || die "Moving package failed"

echo "Gnome -java"
echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_J} ${IUSES_G} ${IUSES_NK}" > ${USEFILE}
emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
quickpkg libreoffice --include-config=y
mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-gnome-java-${BINVERSION}.tbz2  || die "Moving package failed"

cd ${MYTMPDIR}

for name in ./libreoffice-*-${BINVERSION}.tbz2 ; do

  BN=`basename $name .tbz2`

  rm -rf tmp.lo
  mkdir -vp tmp.lo/p1 tmp.lo/p2
  cd tmp.lo/p1

  echo "Unpacking complete archive $BN.tbz2"
  tar xfvjp ../../$BN.tbz2

  echo "Moving debug info"
  mkdir -vp ../p2/usr/lib
  mv -v usr/lib/debug ../p2/usr/lib/

  echo "Re-packing program"
  tar cfv ../../$ARCH-bin-$BN.tar --owner root --group root ./*

  echo "Re-packing debug info"
  cd ../p2
  tar cfv ../../$ARCH-debug-$BN.tar --owner root --group root ./*

  echo "Removing unpacked files"
  cd ../..
  rm -rf tmp.lo

  echo "Removing original package file"
  rm -f $BN.tbz2

#  echo "Moving results to distfiles storage"
#  mv -v $ARCH-bin-$BN.tar.xz $MYDISTDIR
#  mv -v $ARCH-debug-$BN.tar.xz $MYDISTDIR

  echo "Done with $BN.tbz2"

done

cd ${MYTMPDIR}

for package in bin debug ; do

 for suffix in java kde kde-java gnome gnome-java ; do 

  bsdiff ${ARCH}-${package}-libreoffice-${BINVERSION}.tar ${ARCH}-${package}-libreoffice-${suffix}-${BINVERSION}.tar $ARCH-${package}-libreoffice-${suffix}-${BINVERSION}.patch
  xz -9 ${ARCH}-${package}-libreoffice-${suffix}-${BINVERSION}.patch
 # rm ${ARCH}-${package}-libreoffice-${suffix}-${BINVERSION}.tar

 done

 xz -9 ${ARCH}-${package}-libreoffice-${BINVERSION}.tar

done

rm -f ${USEFILE} || die "Removing ${USEFILE} failed"

