#!/usr/bin/python3

import hashlib
from sys import argv
from hashlib import sha256, sha512
from os.path import basename, getsize

def distline(file):
	f = open(file, "br")
	s = f.read()
	f.close()
	wp = hashlib.new("whirlpool")
	wp.update(s)
	return "DIST %s %s SHA256 %s SHA512 %s WHIRLPOOL %s" % (basename(file), getsize(file), sha256(s).hexdigest(), sha512(s).hexdigest(), wp.hexdigest())

for arg in argv[1:]:
	print (distline(arg))
